# Generated by Django 3.1.7 on 2021-03-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0002_document_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploader',
        ),
    ]
